name: platform deployment
on: [push]

jobs:
  create-cluster:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: terraform
    steps:
      - name: check out the repo
        uses: actions/checkout@v2

      - name: install yc
        run: |-
          curl https://storage.yandexcloud.net/yandexcloud-yc/install.sh | bash -s -- -a

      - name: add yc
        run: |-
          sudo cp /home/runner/yandex-cloud/bin/yc /usr/local/bin/yc

      - name: check yc
        run: |-
          yc --version

      - name: setup terraform
        uses: hashicorp/setup-terraform@v1
        with:
          cli_config_credentials_token: ${{ secrets.TF_API_TOKEN }}

      - name: terraform init
        run: terraform init

      - name: terraform apply
        run: terraform apply -auto-approve=true
